name: ci-golang-workflow
on:
  [pull_request]
jobs:
  check-application:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 #pega os dados que foram subidos e envia para a máquina ubuntu
      - uses: actions/setup-go@v2 #prepara o ambiente para rodar o go
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: raonibs/goapp-aluno:latest


